---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: 本節介紹用於 dremio 認證的硬體和軟體。此資訊適用於使用NetApp儲存的 dremio 部署。 
---
= 解決方案概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
混合 Iceberg Lakehouse 解決方案提供了獨特的優勢，以解決資料湖客戶面臨的客戶挑戰。透過利用 Dremio Unified Lakehouse 平台和NetApp ONTAP、 StorageGRID和NetApp Cloud 解決方案，公司可以為其業務營運增加顯著的價值。該解決方案不僅可以存取包括NetApp來源在內的多個資料來源，還可以提高整體分析效能並幫助公司獲得業務洞察力，從而促進業務成長。



== NetApp概述

* NetApp 的產品（例如ONTAP和StorageGRID）可實現儲存和運算的分離，從而根據特定需求實現最佳資源利用率。這種靈活性使客戶能夠使用NetApp存儲解決方案獨立擴展其存儲
* 透過利用 NetApp 的儲存控制器，客戶可以使用 NFS 和 S3 協定有效地向其向量資料庫提供資料。這些協定方便了客戶資料儲存和管理向量資料庫索引，從而無需透過檔案和物件方法存取多個資料副本。
* NetApp ONTAP為 AWS、Azure 和 Google Cloud 等領先的雲端服務供應商提供對 NAS 和物件儲存的原生支援。這種廣泛的兼容性確保了無縫集成，實現了客戶資料移動性、全球可訪問性、災難復原、動態可擴展性和高效能。




=== StorageGRID

我們業界領先的物件儲存 storageGRID 提供了強大的策略引擎，用於自動放置資料、靈活的部署選項以及透過分層擦除編碼實現的無與倫比的耐用性。它具有可擴展的架構，可在單一命名空間中支援數十億個物件和 PB 級資料。該解決方案支援混合雲集成，允許資料分層到主要雲端平台。它在 2019 年 IDC Marketscape 全球基於物件的供應商評估中被評為領導者。

此外，storageGRID 也擅長透過軟體定義的物件儲存、地理冗餘和多站點功能大規模管理非結構化資料。它採用基於策略的資訊生命週期管理，並提供鏡像和搜尋等雲端整合功能。它擁有多項認證，包括通用標準、NF203 數位安全組件、ISO/IEC 25051、畢馬威和科哈塞特合規評估。

總而言之， NetApp storageGRID 提供了強大的功能、可擴展性、混合雲整合和合規性認證，可高效管理大規模非結構化資料。



=== NetApp ONTAP

NetApp ONTAP是一款強大的儲存解決方案，可提供廣泛的企業功能。它包括快照，可提供應用程式一致且防篡改的即時備份。 SnapRestore支援按需近乎即時地恢復備份，而SnapMirror提供整合的遠端備份和災難復原功能。該解決方案還採用了自主勒索軟體保護 (ARP)，透過多管理員驗證、具有 FIPS 認證的靜態資料加密、傳輸中資料加密、多因素身份驗證 (MFA) 和基於角色的存取控制 (RBAC) 等功能確保資料安全。全面的日誌記錄、稽核、板載和外部金鑰管理、安全清除以及多租用戶安全管理進一步增強了資料安全性和合規性。

NetApp ONTAP還具有SnapLock功能，它以較低的總擁有成本提供符合法規的資料保留，具有高水準的完整性、效能和保留。它與NetApp ONTAP 9 完全集成，並提供針對惡意行為、惡意管理員和勒索軟體的保護。

該解決方案包括用於動態資料和靜態資料加密的 NSE/NVE 加密、多因素管理存取和多管理驗證。 Active IQ提供基於 AI 的預測分析和糾正措施，而 QoS 確保服務品質工作負載控制。透過 SysMgr/GUI/CLI/API 可以直觀地實現管理和自動化整合。  FabricPool支援自動資料分層，透過內嵌資料壓縮、重複資料刪除和壓縮提供效率。  NetApp保證滿足工作負載效率目標，且客戶無需承擔任何費用。

NetApp ONTAP支援各種協議，包括 NVMe/FC、FC、NVMe/TCP、iSCSI、NFS、SMB 和 S3，使其成為統一的儲存解決方案。整體而言， NetApp ONTAP提供廣泛的企業功能、強大的安全性、合規性、效率和多功能性，以滿足多樣化的儲存需求。



== Dremio 概述

Dremio 是用於自助分析和人工智慧的統一 Lakehouse 平台。  Dremio 統一分析平台透過 Lakehouse 的靈活性、可擴展性和效能，讓使用者更接近數據，而成本僅為傳統資料倉儲解決方案的一小部分。  Dremio 支援「左移」分析，以消除複雜且昂貴的資料整合和 ETL，提供無需資料移動的無縫企業級分析。  Dremio 還具有以下特點：

* 透過通用語意層和緊密整合的高效能 SQL 查詢引擎實現易於使用的自助服務分析，從而更輕鬆地連接、管理和分析雲端和本地的所有資料。
* Dremio 的 Apache Iceberg 原生 Lakehouse 管理功能簡化了資料發現，並自動化了資料最佳化，透過受 Git 啟發的資料版本控制提供高效能分析。
* Dremio 建立在開源和開放標準的基礎上，幫助企業避免鎖定並保持創新優勢。企業公司信賴 Dremio，認為它是最容易使用的 Lakehouse 平台，在所有工作負載下都具有最佳的性價比。




== Dremio 和NetApp混合 Iceberg Lakehouse 解決方案為客戶帶來什麼價值？

* *改進的資料管理和可訪問性*：Dremio 以其資料湖平台而聞名，該平台使組織能夠直接從其資料湖中高速查詢資料。另一方面， NetApp是雲端資料服務和資料儲存解決方案的領先供應商。該聯合產品為客戶提供了一套全面的解決方案，用於有效地儲存、管理、存取和分析其企業的數據。
* *效能最佳化*：憑藉 NetApp 在資料儲存方面的專業知識以及 Dremio 在資料處理和資料最佳化方面的能力，此合作夥伴關係提供了一種解決方案，可以提高資料操作的效能，減少延遲，並提高業務洞察的速度。  Dremio 甚至為 NetApp 自己的內部 IT 分析基礎架構帶來了效能優勢。
* *可擴充性*：Dremio 和NetApp都提供了可擴充的解決方案。此聯合解決方案為客戶提供高度可擴展的資料儲存、資料管理和分析環境。在混合 Iceberg Lakehouse 環境中，Dremio SQL 查詢引擎與NetApp StorageGRID配對，提供無與倫比的可擴展性、並發性和查詢效能，能夠滿足任何業務的分析需求。
* *資料安全與治理*：兩家公司都非常重視資料安全和治理。它們共同提供強大的安全和資料治理功能，確保資料受到保護並且滿足資料治理要求。基於角色和細粒度的存取控制、全面審計、端到端資料沿襲、統一身分管理以及具有廣泛合規性和安全框架的 SSO 等功能可確保公司的分析資料環境安全且受到管理。
* *成本效益*：透過將 Dremio 的資料湖引擎與 NetApp 的儲存解決方案結合，客戶可以降低與資料管理和資料移動相關的成本。組織也能夠從傳統的資料湖環境遷移到由NetApp和 Dremio 組成的更現代的 Lakehouse 解決方案。此混合 Iceberg Lakehouse 解決方案提供高速查詢效能和市場領先的查詢並發性，可降低 TCO 並縮短業務洞察時間。

