---
sidebar: sidebar 
permalink: software/ai-conf-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: 數據有三種狀態 - 靜止、傳輸和計算。任何人工智慧推理服務的一個重要部分應該是在整個過程中保護資料免受威脅。在推理過程中保護資料至關重要，因為該流程可能會暴露有關外部客戶和提供推理服務的企業的私人資訊。 
---
= 結論
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
數據有三種狀態：靜止、傳輸、計算。任何人工智慧推理服務的一個重要部分應該是在整個過程中保護資料免受威脅。在推理過程中保護資料至關重要，因為該流程可能會暴露有關外部客戶和提供推理服務的企業的私人資訊。 Protopia AI 是當今市場上用於機密 AI 推理的非侵入式純軟體解決方案。借助 Protopia，AI 僅接收資料記錄中對於執行手頭上的 AI/ML 任務至關重要的轉換訊息，僅此而已。這種隨機變換不是一種掩蔽形式，而是基於透過使用精心策劃的雜訊以數學方式改變資料的表示。

具有ONTAP功能的NetApp儲存系統可提供與本地 SSD 儲存相同或更好的效能，並且與NetApp DataOps Toolkit 結合使用，可為資料科學家、資料工程師、AI/ML 開發人員以及業務或企業 IT 決策者帶來以下優勢：

* 在人工智慧系統、分析系統和其他關鍵業務系統之間輕鬆共享資料。這種資料共享減少了基礎設施開銷，提高了效能，並簡化了整個企業的資料管理。
* 獨立可擴展的計算和存儲，以最大限度地降低成本並提高資源利用率。
* 使用整合的 Snapshot 副本和複製來簡化開發和部署工作流程，以實現即時且節省空間的使用者工作區、整合版本控制和自動部署。
* 針對災難復原、業務連續性和監管要求的企業級資料保護和資料治理。
* 簡化資料管理作業的呼叫；從 Jupyter 筆記本中的NetApp DataOps Toolkit 快速取得資料科學家工作區的 Snapshot 副本以進行備份和追溯。


NetApp和 Protopia 解決方案提供了靈活的橫向擴展架構，非常適合企業級 AI 推理部署。它可以實現資料保護並為敏感資訊提供隱私，其中機密的 AI 推理要求可以透過內部部署和混合雲端部署中的負責任的 AI 實踐來滿足。
