---
sidebar: sidebar 
permalink: software/ai-conf-protopia-usecases.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: 數位影像處理具有許多優點，使許多組織能夠充分利用與視覺表示相關的數據。 NetApp和 Protopia 解決方案提供了獨特的 AI 推理設計，以在整個 ML/DL 生命週期中保護和私有化 AI/ML 資料。它使客戶能夠保留敏感資料的所有權，透過緩解與隱私相關的擔憂，使用公共或混合雲部署模型實現規模和效率，並在邊緣部署人工智慧推理。 
---
= 解決方案領域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
數位影像處理具有許多優點，使許多組織能夠充分利用與視覺表示相關的數據。 NetApp和 Protopia 解決方案提供了獨特的 AI 推理設計，以在整個 ML/DL 生命週期中保護和私有化 AI/ML 資料。它使客戶能夠保留敏感資料的所有權，透過緩解與隱私相關的擔憂，使用公共或混合雲部署模型實現規模和效率，並在邊緣部署人工智慧推理。



== 環境情報

在環境危害領域，各行各業可以多種方式利用地理空間分析。政府和公共工程部門可以就公共衛生和天氣狀況獲得可行的見解，以便在流行病或野火等自然災害期間更好地為公眾提供建議。例如，您可以在公共場所（例如機場或醫院）識別 COVID 陽性患者，而不會損害受影響個人的隱私，並提醒相關部門和附近公眾採取必要的安全措施。



== 邊緣設備穿戴裝置

在軍事和戰場上，您可以使用邊緣 AI 推理作為可穿戴設備來追蹤士兵的健康狀況、監控駕駛員行為並向當局發出接近軍用車輛的安全和相關風險警報，同時保護士兵的隱私。軍隊的未來將走向高科技，戰場物聯網 (IoBT) 和軍事物聯網 (IoMT) 將應用於可穿戴作戰裝備，幫助士兵透過使用快速邊緣運算識別敵人並在戰鬥中表現得更好。保護和保存從無人機和穿戴式裝置等邊緣裝置收集的視覺資料對於阻止駭客和敵人至關重要。



== 非戰鬥人員撤離行動

非戰鬥人員撤離行動 (NEO) 由國防部執行，旨在協助將生命受到威脅的美國公民和國民、國防部文職人員以及指定人員（東道國 (HN) 和第三國國民 (TCN)）撤離到適當的安全避難所。現有的行政控制措施主要採用手動的撤離人員篩選流程。然而，透過使用高度自動化的 AI/ML 工具結合 AI/ML 視訊混淆技術，可以提高撤離人員識別、撤離人員追蹤和威脅篩選的準確性、安全性和速度。



== 醫療保健和生物醫學研究

影像處理用於根據電腦斷層掃描 (CT) 或磁振造影 (MRI) 獲得的 3D 影像診斷手術規劃的病理。 HIPAA 隱私規則規定了組織如何收集、處理和刪除所有個人資訊和照片等數位影像。根據 HIPAA 安全港規定，要使資料符合可共享條件，必須刪除正面照片和任何類似影像。用於從結構 CT/MR 影像中隱藏個人臉部特徵的去識別或顱骨剝離演算法等自動化技術已成為生物醫學研究機構資料共享過程的重要組成部分。



== AI/ML分析的雲端遷移

企業客戶傳統上在本地訓練和部署 AI/ML 模型。出於規模經濟和效率的原因，這些客戶正在擴展以將 AI/ML 功能轉移到公共、混合或多雲部署。然而，它們受到可以向其他基礎設施公開的數據的限制。  NetApp解決方案可應對各種網路安全威脅， https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["資料保護"^]和安全評估，並與 Protopia 資料轉換結合，最大限度地降低將影像處理 AI/ML 工作負載遷移到雲端所帶來的風險。

有關其他行業的邊緣運算和 AI 推理的更多用例，請參閱link:../infra/ai-lenovo-edge-intro.html["TR-4886 邊緣人工智慧推理"^]以及NetApp AI 博客， https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["情報與隱私"^] 。
