---
sidebar: sidebar 
permalink: software/ai-nvaie-vmw-tech.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise 與NetApp和 VMware 合作 - 技術概述 
---
= 技術概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本節概述了NVIDIA AI Enterprise 與NetApp和 VMware 的技術。



== NVIDIA AI 企業版

NVIDIA AI Enterprise 是一款端到端、雲端原生的 AI 和資料分析軟體套件，經過NVIDIA優化、認證和支持，可在具有NVIDIA認證系統的 VMware vSphere 上運行。該軟體有助於在現代混合雲環境中簡單、快速地部署、管理和擴展 AI 工作負載。



== NVIDIA GPU 雲端 (NGC)

NVIDIA NGC 為 AI 從業者提供了一系列針對 GPU 最佳化的軟體，以開發他們的 AI 解決方案。它還提供對各種 AI 服務的訪問，包括用於模型訓練的NVIDIA Base Command、用於部署和監控模型的NVIDIA Fleet Command 以及用於安全存取和管理專有 AI 軟體的 NGC Private Registry。此外， NVIDIA AI Enterprise 客戶可以透過 NGC 入口網站請求支援。



== VMware vSphere

VMware vSphere 是 VMware 的虛擬化平台，它將資料中心轉變為包含 CPU、儲存和網路資源的聚合運算基礎架構。 vSphere 將這些基礎架構作為統一的操作環境進行管理，並為管理員提供管理該環境中資料中心的工具。

vSphere 的兩個核心元件是 ESXi 和 vCenter Server。  ESXi 是管理員創建和運行虛擬機器及虛擬設備的虛擬化平台。 vCenter Server 是管理員管理網路中連接的多台主機並池化主機資源的服務。



== NetApp ONTAP

ONTAP 9 是NetApp最新一代儲存管理軟體，它支援企業實現基礎架構現代化並過渡到雲端就緒資料中心。 ONTAP利用業界領先的數據管理功能，只需一套工具即可管理和保護數據，無論數據位於何處。您也可以將資料自由移動到任何需要的地方：邊緣、核心或雲端。  ONTAP 9 包含眾多功能，可簡化資料管理、加速和保護關鍵數據，並支援跨混合雲架構的下一代基礎架構功能。



=== 簡化資料管理

資料管理對於企業 IT 營運和資料科學家至關重要，以便將適當的資源用於 AI 應用程式和訓練 AI/ML 資料集。以下有關NetApp技術的附加資訊超出了本次驗證的範圍，但可能與您的部署相關。

ONTAP資料管理軟體包括以下功能，可簡化操作並降低總營運成本：

* 內聯資料壓縮和擴展重複資料刪除。資料壓縮減少了儲存區塊內部浪費的空間，重複資料刪除顯著增加了有效容量。這適用於本地儲存的資料和分層到雲端的資料。
* 最小、最大和自適應服務品質 (AQoS)。細粒度的服務品質 (QoS) 控制有助於維持高度共享環境中關鍵應用程式的效能水準。
* NetApp FabricPool。提供冷資料到公有和私有雲儲存選項的自動分層，包括 Amazon Web Services (AWS)、Azure 和NetApp StorageGRID儲存解決方案。有關FabricPool的更多信息，請參閱 https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598： FabricPool最佳實踐"^]。




=== 加速並保護數據

ONTAP提供卓越等級的效能和資料保護，並透過以下方式擴展這些功能：

* 性能和更低的延遲。  ONTAP以盡可能低的延遲提供盡可能高的吞吐量。
* 資料保護。  ONTAP提供內建資料保護功能，並在所有平台上提供通用管理。
* NetApp磁碟區加密 (NVE)。  ONTAP提供原生磁碟區級加密，同時支援板載和外部金鑰管理。
* 多租戶和多因素身份驗證。  ONTAP支援以最高等級的安全性共用基礎架構資源。




=== 面向未來的基礎設施

ONTAP具有以下功能，可協助滿足嚴苛且不斷變化的業務需求：

* 無縫擴展和無中斷運行。 ONTAP支援無中斷地向現有控制器和橫向擴展叢集添加容量。客戶可以升級到最新技術，例如 NVMe 和 32Gb FC，而無需昂貴的資料遷移或中斷。
* 雲端連線。  ONTAP是與雲端連接最緊密的儲存管理軟體，在所有公有雲中均提供軟體定義儲存（ONTAP Select）和Google Cloud NetApp Volumes Volumes ）的選項。
* 與新興應用程式的整合。  ONTAP使用支援現有企業應用的相同基礎架構，為下一代平台和應用（如自動駕駛汽車、智慧城市和工業 4.0）提供企業級資料服務。




== NetApp DataOps 工具包

NetApp DataOps Toolkit 是一款基於 Python 的工具，可簡化由高效能、橫向擴展NetApp儲存支援的開發/培訓工作區和推理伺服器的管理。主要功能包括：

* 快速配置由高效能、橫向擴充NetApp儲存支援的新的高容量 JupyterLab 工作區。
* 快速配置由企業級NetApp儲存支援的全新NVIDIA Triton 推理伺服器實例。
* 近乎即時地克隆高容量的 JupyterLab 工作區，以實現實驗或快速迭代。
* 幾乎即時地保存高容量 JupyterLab 工作區的快照，以用於備份和/或可追溯性/基準測試。
* 近乎即時地提供、複製和快照大容量、高效能資料磁碟區。

